version: "3.8"
services:
    lexi:
        image: ghcr.io/ucrel/lexidb:0.1.1
        volumes:
            - ./test_files/lexi-data/bl-books:/data/lexi-data/bl-books
            - ./test_files/app.properties:/lexidb/app.properties
            - ./test_files/log4j.properties:/lexidb/log4j.properties
        networks:
            - backend
        restart: unless-stopped
        user: $USER
        entrypoint: java
        command: -Dlog4j.configuration=file:/lexidb/log4j.properties -jar lexidb-2.0.jar /lexidb/app.properties
    web:
        image: nginxinc/nginx-unprivileged:1.20-alpine
        depends_on:
            - lexi
        ports:
            - 127.0.0.1:80:8080
        user: nobody
        volumes:
            - ./website:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - frontend
            - backend
        restart: unless-stopped

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge