version: "3.8"
services:
    lexi:
        image: ghcr.io/ucrel/lexidb:0.1.1
        volumes:
            - ./test_files/lexi-data/bl-books:/data/lexi-data/bl-books
            - ./test_files/app.properties:/lexidb/app.properties
        networks:
            - backend
        restart: unless-stopped
    web:
        image: nginx:1.20-alpine
        depends_on:
            - lexi
        ports:
            - 127.0.0.1:8080:80
        volumes:
            - ./website:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - frontend
            - backend
        restart: unless-stopped

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge